### ISSUE TITLE
⚙️ 올리브영 제목에 이모티콘이 있어서 mysql 스키마 타입을 utf8mb4로 바꿔야 할 것 같습니다.

### ISSUE THREAD

**Issue by Seung-zedd** [Team-3-SnapEvent/SnapEvent-backend#12]
![image](https://github.com/Team-3-SnapEvent/SnapEvent-backend/assets/101092038/0fce1bd5-ca1c-4882-8760-1b034035b865)
본인 디비 스키마 타입에서 렌치 모양을 누르시면 위의 그림과 같이 뜨는데요 여기서 Charset 부분 드롭박스 왼쪽만 utf8mb4로 바꾸시면 오른쪽은 자동으로 맞춰주니까 이렇게 변경해주시면 좋을 것 같아요 :)

**Comment by dahoon7151** [comment]
넵 확인했습니다~
