### ISSUE TITLE
⚙️ 현재 Site, Event 도메인이 있는데 이 둘은 없어도 괜찮을 것 같습니다.

### ISSUE THREAD

**Issue by Seung-zedd** [Team-3-SnapEvent/SnapEvent-backend#24]
도메인을 정리해보니까, 크롤링, 알림, 구독, 멤버 이렇게 4개로 간소화가 되는데요.
![image](https://github.com/Team-3-SnapEvent/SnapEvent-backend/assets/101092038/e4ae5957-581d-44a4-b523-73116ea95fc7)
위와 같이 온보딩에 있는 구독체크 버튼을 보니까:

구독체크: 사용자가 토글형식으로 체크해제 -> boolean isSubscribed를 crawlDto 및 엔티티에 추가한 후, getCheckedCrawlDto() api로 구독한 리스트 확인가능하게 하면 어떨까요?
=> 크롤링 관련 도메인은 제가 수정해보겠습니다. (구독하고 크롤링 도메인을 연결하려고 보니 상당히 어렵네요 😅 )

- 추가로, 크롤링 api를 호출하면 크롤링 서비스 로직이 크롤링 데이터들을 크롤링 리포지토리에 저장하니까,  crawlingRepository.existsByIsSubscribed()로 True 값이 있는 crawlDto들만 보여주면 될 것 같아요

정리하자면, 온보딩 페이지에서 크롤링한 리스트를 보여주는 api는 /api/crawl/* 로 기존의 것들로 호출하고, 
마이페이지의 "내가 구독한 브랜드 리스트" 조회는 따로 GET /api/subscriptions/{구독 리스트pk}와 같이 추가해야 할 것 같은데 어떻게 생각하시나요?

위의 사항들은 대략 이런 방향으로 흘러가면 좋을 것 같다라는 제 개인적인 의견을 표출한 것에 불과하기 때문에, 다훈님이 따로 원하시는 로직이 있으시면 그 로직으로 구현하셔도 좋습니당

**Comment by dahoon7151** [comment]
확인했습니다!
제가 이미 구독 기능쪽 구현을 다 해놔서 site, event 엔티티는 삭제한 채로 develop에 푸시해둘게요
