### ISSUE TITLE
🐛 Follower 엔티티에 hibernate가 매핑하는데 오류가 있습니다.

### ISSUE THREAD

**Issue by Seung-zedd** [Team-3-SnapEvent/SnapEvent-backend#5]
`@Type(JsonType.class)
    @Column
    private Map<String, String> subList;`
이 부분인데요, 어떻게 해결하는게 좋을까요? 이 부분은 화요일에 토의해봅시다.

**Comment by dahoon7151** [comment]
엔티티 컬럼 안에 구독목록을 json 형태로 넣으려고 한건데 꼭 json형태로 저장할 필요는 없어서
리스트를 string 형식으로 저장하도록 수정해서 push 해두겠습니다.
https://khdscor.tistory.com/39

**Comment by dahoon7151** [comment]
string 형식으로 변환하는거보다 위 링크 2번 방식이 훨씬 더 간단해서 그렇게 수정하였습니다

**Comment by Seung-zedd** [comment]
> string 형식으로 변환하는거보다 위 링크 2번 방식이 훨씬 더 간단해서 그렇게 수정하였습니다

오! 좋습니다 저도 값 타입 컬렉션인 `@ElementCollection`을 생각했었는데 수정 잘 해주셨어요 :)
